### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by ShaneSharareh** [ShaneSharareh/bettercraft#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/` check
- [x] Has working demo login
- [x] Smooth, bug free navigation check

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`check
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page check
- [x] Errors should display for both `/signup` and `/login`. check
- [x] Errors should clear when moving between `/signup` and `/login`.check
- [x] Can sign up a user check 
- [x] Can sign in as a user check
- [x] Can log out a user check
- [x] Can't sign up with the same username/email check
- [x] Pressing enter after filling out the session form should use the form data, not the demo user 

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in 

## Style

- [ ] The site should look exactly like the actual site check check 
- [x] All relevant elements should have `cursor: pointer` on hover check
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production check

## Seeds
- [x] Adequate and appropriate seeds

**Comment by mkayys** [comment]
-I would suggest a different font for anywhere your webpage uses `Times New Roman`
- styling needed for session forms:
![Screen Shot 2020-12-15 at 9 23 55 AM](https://user-images.githubusercontent.com/48598856/102250034-e6613680-3eb7-11eb-8ab9-a9fb0fc5d535.png)
- buttons are to the left; errors need styling
- reference: 
![Screen Shot 2020-12-15 at 9 29 19 AM](https://user-images.githubusercontent.com/48598856/102250144-07c22280-3eb8-11eb-9dbc-292e8cb1ff9b.png)

**Comment by mkayys** [comment]
- highly recommend changing font; I think the font on etsy may be custom, the "Graphik Webfont"; It looks like the next closest font would be `Roboto` which is free and available on google fonts.
- I would add some space between your error message and input label; also recommend removing the blue highlight around the button when clicked as seen below
![Screen Shot 2020-12-16 at 5 17 16 PM](https://user-images.githubusercontent.com/48598856/102425674-a044c980-3fc2-11eb-9f19-2f3f603758d1.png)
